### PR TITLE
Update README.md characterSets => charactersSets

### PR DESCRIPTION
**Pull request by icepy**
change README.md  characterSets => charactersSets

### CODE REVIEW

**Comment by smallhadroncollider** [comment]
Well spotted. It should really be the import that's changed to `characterSets` - if you want to update the commit I'll merge it in.

**Comment by icepy** [comment]
y ,  merge it in.

**Comment by smallhadroncollider** [comment]
If you want me to merge it you'll need to update the commit so that it changes the `import` statement rather than the line where it's used.

**Comment by icepy** [comment]
done

**Comment by smallhadroncollider** [comment]
Thanks!

**Pull request merged**
